### ISSUE TITLE
have you ever found a fix for this?

### ISSUE THREAD

**Issue by romk1n** [lachlanhurst/SceneKitOffscreenRendering#1]
sorry meant to say for memory leak, thanks!

**Comment by lachlanhurst** [comment]
@romk1n the Apple Bug Report I filed was marked as resolved, so I believe they did actually fix it up. The fix should certainly be in any version of iOS10.

Are you still seeing it? I haven't confirmed if it has been resolved.

**Comment by tiepvuvan** [comment]
Facing exactly same problem with iOS 10.2 :( did you find any workaround?

**Comment by lachlanhurst** [comment]
@tiepvuvan I just updated the code in this repo to Swift 3 as I'd never tested if it had been resolved. I left it running for 10 minutes or so and didn't see any memory leaks, so I believe this has been fixed.

I'm now on a different phone, that could have something to do with it.

**Comment by dustinfreeman** [comment]
FYI those in this thread, I recently created a pull request for iOS 11. I don't see any memory leak. #3

**Comment by lachlanhurst** [comment]
Thanks for the PR @dustinfreeman !

Closing this issue as Apple seem to have resolved this some time ago.
