### ISSUE TITLE
Compile error at `setupMetal`

### ISSUE THREAD

**Issue by hajimehoshi** [lachlanhurst/SceneKitOffscreenRendering#4]
```
    func setupMetal() {
        if self.scnView1.renderingAPI == SCNRenderingAPI.metal {
            device = scnView1.device
            commandQueue = device.makeCommandQueue()
            renderer = SCNRenderer(device: device, options: nil)
        } else {
            fatalError("Sorry, Metal only")
        }
    }
```

Error message:

```
Value of type 'SCNView?' has no member 'device'
```

**Comment by dustinfreeman** [comment]
@hajimehoshi This sounds like an SceneKit API version issue. What version of iOS are you building on? This builds on iOS 12 for me.

**Comment by hajimehoshi** [comment]
I was using macOS Mojave. I've not tested to build this for iOS.

**Comment by dustinfreeman** [comment]
Looks like your error comes from building for the iOS device Simulator, where SCNView.device is not valid. You'll need an actual device – I'm not sure if there's an alternative to run the code as-is.

**Comment by lachlanhurst** [comment]
Unfortunately the issue as @dustinfreeman said is that the iOS simulator doesn't support Metal so this example wont work.

I've updated the code (a4ebe0c5acb482c06d5fdf710a5ef11bc37db322) so it'll now compile on the simulator, and then give a better error message when it fails.

Hopefully Apple adds support one day, till then I'll close this.
